### ISSUE TITLE
Add the client certificates to download at https://mtls.run/pt/sidecar

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/mtls-best-friend#11]
At this page there are the server certificates and there is a `curl` example, but the `curl` uses a client key/cert that is not available to download. 

These files can be downloaded at https://mtls.run/pt/ambassador

**Comment by cristiangutie** [comment]
Hi @tiagostutz! I would like to claim this issue.

**Comment by tiagostutz** [comment]
Hi @cristiangutie 👋 
Awsome.! Thanks for your help.

I just assigned this to you. If you need any assistance, please let me know.

**Comment by cristiangutie** [comment]
@tiagostutz I made a pull request (#12). Please review it.
